files pushed to associates
CarvingIT/WiseIntern pull request #48
Opened 2021-05-23 14:38 UTC by truptikulkarni

Files pushed to associates branch. Plz check the updated files.

2021-05-24 03:31 UTC, ketan404 requested changes
Some updates needed.
* Name the controller AssociateController.
* In the model, use timestamps. You may have to write a migration for adding relevant columns.
* Do not make any change to config/database.php. That file needs to be restored. Please add your db connection config in .env file.
* Name the view file associate-form.blade.php
* The view should extend app layout, which is for the logged in users.
* Associate type field should be a select with two values - Company and Individual
* Apply middleware 'admin' to both the routes related to this.

2021-05-27 14:32 UTC, ketan404 reviewed
Please do these changes.

Restore config/database.php. No changes are needed here.

Routes having admin middleware should have the prefix 'admin/'.

Post route may be changed to  /admin/save-associate.

Redirect to the list of associates after saving. It's okay if that page currently has nothing. You will need a new route for this.

2021-05-27 14:59 UTC, truptikulkarni commented
Ok ,I'll do the changes as you suggest.But I'm not able to do pull request
from github.com.
Thanks and Regards,
Trupti

On Thu, 27 May 2021, 20:03 Ketan Kulkarni, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Please do these changes.
>
> Restore config/database.php. No changes are needed here.
>
> Routes having admin middleware should have the prefix 'admin/'.
>
> Post route may be changed to /admin/save-associate.
>
> Redirect to the list of associates after saving. It's okay if that page
> currently has nothing. You will need a new route for this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CarvingIT/WiseIntern/pull/48#pullrequestreview-670263819>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AB4N6D6JF5MOYXCX23YTE73TPZJ2HANCNFSM45LYVKOA>
> .
>

2021-05-31 13:49 UTC, ketan404 approved these changes

2021-05-31 13:49 UTC, merged